name: Daily Telegram Reminder

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 9:00 AM WAT (UTC+1)
  workflow_dispatch:     # Manual trigger option

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run reminder script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python send_reminder.py
